/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.blakfx.crypto;

public interface helixConstants {
  public final static int HELIX_INTERFACE_VERSION = 0x0002;
  public final static int LOG_NETWORK = 1;
  public final static int LOG_PRINTF = 2;
  public final static int LOG_FILE = 4;
  public final static int LOG_DATABASE = 8;
  public final static int LOG_NEW_FILE = 1;
  public final static int LOG_APPEND_FILE = 2;
}
