/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.blakfx.crypto;

public class helixJNI {
  public final static native byte[] cdata(long jarg1, int jarg2);
  public final static native void memmove(long jarg1, byte[] jarg2);
  public final static native void imaxdiv_t_quot_set(long jarg1, imaxdiv_t jarg1_, long jarg2);
  public final static native long imaxdiv_t_quot_get(long jarg1, imaxdiv_t jarg1_);
  public final static native void imaxdiv_t_rem_set(long jarg1, imaxdiv_t jarg1_, long jarg2);
  public final static native long imaxdiv_t_rem_get(long jarg1, imaxdiv_t jarg1_);
  public final static native long new_imaxdiv_t();
  public final static native void delete_imaxdiv_t(long jarg1);
  public final static native long imaxabs(long jarg1);
  public final static native long imaxdiv(long jarg1, long jarg2);
  public final static native long strtoimax(String jarg1, long jarg2, int jarg3);
  public final static native java.math.BigInteger strtoumax(String jarg1, long jarg2, int jarg3);
  public final static native void LOCAL_USER_ID_set(java.math.BigInteger jarg1);
  public final static native java.math.BigInteger LOCAL_USER_ID_get();
  public final static native void SERVER_DELAY_RESPONSE_TIME_set(int jarg1);
  public final static native int SERVER_DELAY_RESPONSE_TIME_get();
  public final static native void logger_setLogLevel(int jarg1);
  public final static native int logger_getLogLevel();
  public final static native void logger_enableLogLevelFlag(long jarg1);
  public final static native void logger_disableLogLevelFlag(long jarg1);
  public final static native void setLogOutputFile(String jarg1, long jarg2);
  public final static native void setLogOutputDatabaseFile(String jarg1, long jarg2);
  public final static native java.math.BigInteger jCrypto_simpleSearchForRecipientByName(String jarg1, long jarg2);
  public final static native java.math.BigInteger jCrypto_simpleSearchForRecipientByEmail(String jarg1, long jarg2);
  public final static native int jCrypto_userValidate(java.math.BigInteger jarg1);
  public final static native int jCrypto_userRelease(java.math.BigInteger jarg1);
  public final static native int void2int(long jarg1);
  public final static native String void2str(long jarg1);
  public final static native java.math.BigInteger jCrypto_encryptStart(java.math.BigInteger jarg1, String jarg2, long jarg3, String jarg4);
  public final static native byte[] jCrypto_encryptGetOutputData(java.math.BigInteger jarg1);
  public final static native int jCrypto_encryptOutputExists(java.math.BigInteger jarg1);
  public final static native int jCrypto_encryptConclude(java.math.BigInteger jarg1);
  public final static native java.math.BigInteger jCrypto_decryptStart(byte[] jarg1, String jarg3);
  public final static native byte[] jCrypto_decryptGetOutputData(java.math.BigInteger jarg1);
  public final static native int jCrypto_decryptConclude(java.math.BigInteger jarg1);
  public final static native int jCrypto_decryptOutputExists(java.math.BigInteger jarg1);
  public final static native int jCrypto_serverIsConnected();
  public final static native int jCrypto_serverDisconnect();
  public final static native int jCrypto_serverConnect();
  public final static native int jCrypto_waitEvent(java.math.BigInteger jarg1, long jarg2);
  public final static native int jCrypto_waitEventStatus(java.math.BigInteger jarg1);
  public final static native int jPromiseManager_getStatus(java.math.BigInteger jarg1);
  public final static native long jPromiseManager_getUserData(java.math.BigInteger jarg1, java.math.BigInteger jarg2);
  public final static native int jCrypto_apiStartup(String jarg1, int jarg2, long jarg3);
  public final static native int jCrypto_apiStartup_Advanced(String jarg1, int jarg2, String jarg3, long jarg4);
  public final static native void jCrypto_apiShutdown();
  public final static native int jCrypto_accountCreate(String jarg1);
  public final static native int jCrypto_accountLogin(String jarg1);
  public final static native long jCrypto_accountDelete(String jarg1);
}
