/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.blakfx.crypto;

public class imaxdiv_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected imaxdiv_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(imaxdiv_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        helixJNI.delete_imaxdiv_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setQuot(long value) {
    helixJNI.imaxdiv_t_quot_set(swigCPtr, this, value);
  }

  public long getQuot() {
    return helixJNI.imaxdiv_t_quot_get(swigCPtr, this);
  }

  public void setRem(long value) {
    helixJNI.imaxdiv_t_rem_set(swigCPtr, this, value);
  }

  public long getRem() {
    return helixJNI.imaxdiv_t_rem_get(swigCPtr, this);
  }

  public imaxdiv_t() {
    this(helixJNI.new_imaxdiv_t(), true);
  }

}
