/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.blakfx.crypto;

public final class logLevel_t {
  public final static logLevel_t NO_LOG = new logLevel_t("NO_LOG", 0x00);
  public final static logLevel_t ERROR_LEVEL = new logLevel_t("ERROR_LEVEL", 0x01);
  public final static logLevel_t INFO_LEVEL = new logLevel_t("INFO_LEVEL", 0x02);
  public final static logLevel_t WARN_LEVEL = new logLevel_t("WARN_LEVEL", 0x04);
  public final static logLevel_t DEBUG_LEVEL = new logLevel_t("DEBUG_LEVEL", 0x06);
  public final static logLevel_t ALL_LEVEL = new logLevel_t("ALL_LEVEL", 0xffff);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static logLevel_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + logLevel_t.class + " with value " + swigValue);
  }

  private logLevel_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private logLevel_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private logLevel_t(String swigName, logLevel_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static logLevel_t[] swigValues = { NO_LOG, ERROR_LEVEL, INFO_LEVEL, WARN_LEVEL, DEBUG_LEVEL, ALL_LEVEL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

