/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.blakfx.crypto;

public final class option_t {
  public final static option_t USER_OWNS_MEMORY = new option_t("USER_OWNS_MEMORY", 0x0000);
  public final static option_t HELIX_OWNS_MEMORY = new option_t("HELIX_OWNS_MEMORY", 0x0001);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static option_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + option_t.class + " with value " + swigValue);
  }

  private option_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private option_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private option_t(String swigName, option_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static option_t[] swigValues = { USER_OWNS_MEMORY, HELIX_OWNS_MEMORY };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

