/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.blakfx.crypto;

public final class serverResponseCode_t {
  public final static serverResponseCode_t SERVER_SUCCESS = new serverResponseCode_t("SERVER_SUCCESS", 0);
  public final static serverResponseCode_t SERVER_FAIL = new serverResponseCode_t("SERVER_FAIL", -1);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static serverResponseCode_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + serverResponseCode_t.class + " with value " + swigValue);
  }

  private serverResponseCode_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private serverResponseCode_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private serverResponseCode_t(String swigName, serverResponseCode_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static serverResponseCode_t[] swigValues = { SERVER_SUCCESS, SERVER_FAIL };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

